FROM redis:3.2.8

RUN mkdir -p /data/db && mkdir -p /data/log && mkdir -p /usr/local/etc/redis/ && touch /usr/local/etc/redis/redis.conf  && chown -R redis:redis /data/db && chown -R redis:redis /data/log

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
#CMD ["redis-server"]
